version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
