[package]
name = "dev_utils"
version = "0.1.1"
authors = ["Jeroen Van Der Donckt"]
edition = "2021"
description = "Shared utilities for development (tests & benchmarks)"

[dependencies]
ndarray = "0.15.6"
rand = "0.7.2"
rand_distr = "0.2.2"
