[package]
name = "dev_utils"
version = "0.1.0"
authors = ["Jeroen Van Der Donckt"]
edition = "2021"
description = "Shared utilities for development (tests & benchmarks)"

[dependencies]
numpy = "0.17.2"
rand = "0.7.2"
rand_distr = "0.2.2"
