name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: argminmax test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macOS-latest', 'ubuntu-latest']
        rust: ['stable', 'beta', 'nightly']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: Rust toolchain info
          run: |
            cargo --version --verbose
            rustc --version
            cargo clippy --version    
            cargo fmt --version

      - name: Linting
        run: |
          cargo fmt -- --check
          cargo clippy --features half -- -D warnings

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--features half -- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
